apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cffv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cffv
    app.kubernetes.io/part-of: byoc-app-vqwk
  name: cffv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: cffv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: cffv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ghfb-tenant/byoc-app-vqwk/cffv@sha256:4528f0885f663b326f1be388e90899d628cc9a6a52eb72f74684c8476a58487d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
